### ISSUE TITLE
EXTBAN ISupport support

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#159]

**Comment by Zarthus** [comment]
What exactly do we want to receive here? Some sort of mapping like `channel.getExtbanHelper().accountBan(User nick, @Nullable Mask fallbackBanmask)`?

Or do you just want to get the `ISupport.supports(ISupport.EXTBAN)`? Because then it sounds like KICL is missing some ISupport functionality, and not EXTBAN support specifically

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/bd79dd71532fffd0763d74e9316098a611fc61e4

Added ISUPPORT support for 7.0.0
