### ISSUE TITLE
Make documentation for common problems

### ISSUE THREAD

**Issue by AKPWebDesign** [KittehOrg/KittehIRCClientLib#193]
@mbax asked for this issue to be created, so here it is. It'd be really helpful to have a page dedicated to frequently encountered problems and their solutions.

**Comment by mbax** [comment]
Thanks!

Some common problems I'm thinking of:

"Oh no an exception" - Exceptions are fine, by default things print to console. Link to documentation on exception listening.

"Oh no 004 missing version" - Damn Twitch. Link to twitch stuffs.

**Comment by mbax** [comment]
Would appreciate input from others.

Another one, though not sure how to describe it: SSL-related errors. Maybe more than one for this, with the different issues you can hit when trying to connect. 

* Exception when connecting to server that doesn't run SSL on 6697
* Exception when connecting to 6667 without disabling SSL
* Cert not recognized
  * LetsEncrypt has a minimum JRE version
  * WoSign (/StartCom)

**Comment by Zarthus** [comment]
The STS machine lol768 implemented gets quite a few questions, specifically the nag exception (somewhat related to others, but never specifically mentioned in here)

**Comment by mbax** [comment]
## An exception printed to console!

If KICL cannot parse a message type that it is written to handle, it will create a detailed exception for this problem. This sort of exception does not halt processing of further messages, and does not cause KICL to disconnect from the server or otherwise die. By default, KICL outputs its various exceptions to console. To change this behavior, utilize `Client.Builder#listenException(Consumer<Exception>)` during the build phase or `Client#setExceptionListener(Consumer<Exception> listener)` later on.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/compare/documentation

**Comment by mbax** [comment]
A little late https://github.com/KittehOrg/KittehIRCClientLib/commit/c989b58da492c68d020e54e2fe85b90ddaf320a0
