### ISSUE TITLE
Improve client builder

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#227]
Move "management" setters behind a `management()` method:
```java
Client.builder()
  .nick("kitten")
  .management() // returns Client$Builder$Management
    .capabilityManager(...)
    .then() // returns Client$Builder
  .build()
```

Refactor methods:
- existing `webirc` method takes *all* parameters, but for server we have `serverHost`, `serverPort`, `serverPassword` - we should either split `webirc` into separate methods, or merge the server/bind/etc into a single methods
- `webircRemove` should be removed, and pass `null` to `webirc`* instead
- `iSupportManager` is an awkward method name

**Comment by mbax** [comment]
Management I like and have no issues with.
WEBIRC I have as one because you need all of it for WEBIRC, as one thing, but don't need serverHost/Port/Password together or even need them. But yeah that's why the removal exists. Mrrph. I'm not sure how to solve something that needs to be all or nothing. Maybe a forced builder path?

Any advice for ISUPPORT?

**Comment by kashike** [comment]
```
    Client.builder()
      .nick("kitten")
      .management() // returns Client$Builder$Management
        .capabilityManager(...)
        .then() // returns Client$Builder
      .webirc() // returns Client$Builder$WebIRC
        .password("hunter2") // @Nullable
        .user("billgates") // @Nullable
        .host("amazon.cat") // @Nullable
        .ip(ok) // @Nullable
        .then() // returns Client$Builder
      .build()
```

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/pull/228 merged
