### ISSUE TITLE
My bot does not connect on my channel

### ISSUE THREAD

**Issue by CoreException1312** [KittehOrg/KittehIRCClientLib#296]
Hello,
I have already created a UnrealIRCd Sever on my root and actually have the bot ready so it should connect on my channel. But unfortunately it does not. In the console comes no exception or anything else. By the way, when I ask if the ChannelList is empty, the console displays true.
I am just new in this area, so it is possible that it is a totally dumb error. 
Thanks in advance

Here is my Main class:

`

    public static class Listener {
        @Handler
        public void meow(ChannelJoinEvent event) {
            System.out.println("I am connected!");
        }

        @CommandFilter("PRIVMSG")
        @Handler
        public void privmsg(ClientReceiveCommandEvent event) {
            System.out.println("We get signal!");
        }

    }

    public static void main(String[] args) {
        Client client = Client.builder()
                .server().host("MY_SERVER").port(443)
                .password("oauth:MY_OAUTH_TOKEN").then()
                .nick("corebot")
                .build();
        TwitchSupport.addSupport(client);
        client.getEventManager().registerEventListener(new Listener());
        client.addChannel("#coreexception");
        client.connect();
        client.sendMessage("#coreexception", "I'm here! :)");
        System.out.println("Bot started!");
        //client.getChannels().forEach(channel -> System.out.println(channel.getName()));
        if (client.getChannels().isEmpty()) System.out.println(true);

    }
`

**Comment by mbax** [comment]
Howdy! I think it's worth doing some basic debugging on what the server is sending back. Check out the debugging section here and set it up like what's given as example: 
https://kitteh-irc-client-library.readthedocs.io/en/latest/#getting-started

A couple things to keep in mind as well:
* You are calling sendMessage before the bot has joined the channel, which may result in that being sent prior to joining the channel. Probably worth doing that in the join event listener too.
* Calling getChannels when you do, will almost certainly be empty because the client won't have joined within the nanoseconds since connect() was called. It probably hasn't even finished opening the connection by then.
* Don't do the TwitchSupport feature if connecting to your own server. It tweaks behavior a bit to handle Twitch's slightly out-of-spec setup.

These probably won't be the cause of the overall not-actually-joining issue, though, so I'll be interested to see the debugging output.

**Comment by CoreException1312** [comment]
Hey thanks for your help! I did the debugging and got the following result:

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Bot started!
33:38 [O] CAP LS 302
33:38 [O] PASS oauth:MY_OAUTH_TOKEN
33:38 [O] USER Kitteh 8 * :KICL 7.4.0 - kitteh.org
33:38 [O] NICK corebot
33:38 [I] HTTP/1.1 400 Bad Request
33:38 [I] Date: Sun, 21 Feb 2021 10:33:38 GMT
33:38 [I] Server: Apache/2.4.38 (Debian)
33:38 [I] Content-Length: 308
33:38 [I] Connection: close
33:38 [I] Content-Type: text/html; charset=iso-8859-1
33:38 [I] 
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

I guess I made a mistake while setting up the UnrealIRCd server. What I can say in any case is that I made the host to my website which has a valid HTTPS certificate. And I connect through a domain. Or the website may not be HTTPS at all?

With best regards
CoreException

**Comment by mbax** [comment]
Probably want to give it the port unreal is using rather than the httpd port 😁 

Have a great day!
